# theme = "tokyonight_storm"
theme = "base16_transparent"
[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
G = "goto_file_end"
X = "extend_line_above"
ret = ["move_line_down", "goto_line_start"]

[keys.normal.g]
q = ":reflow"

[keys.normal.space]
q = ":quit"
w = ":write"

