#!/bin/sh
alias j='z'
alias f='zi'
alias g='lazygit'
alias gg='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias ccat='pygmentize -g'
alias python='python3'
alias vi="lvim"
alias hx="helix"
alias idea=".local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/231.9011.34/bin/idea.sh"

#alias lvim='nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"'
alias lvim='~/.local/bin/lvim'
alias lvim_config="rm -f ~/.config/lvim/config.lua && cd ~/my-dotfiles && stow lvim"
alias lvim-config="rm -f ~/.config/lvim/config.lua && cd ~/my-dotfiles && stow lvim"
alias lvim_uninstall='bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh'
alias lvim-uninstall='bash ~/.local/share/lunarvim/lvim/utils/installer/uninstall.sh'
alias lvim-install="LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh)"
alias lvim_install="LV_BRANCH='release-1.2/neovim-0.8' bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/fc6873809934917b470bff1b072171879899a36b/utils/installer/install.sh)"

# Webapps
alias kiosk-chrome="google-chrome-unstable --user-data-dir=\"~/.config/google-chrome/KioskProfile\""
alias kiosk-browser="kiosk-chrome"

alias mypurge='sudo apt-get purge --auto-remove'
alias myprune='sudo apt-get purge --auto-remove'

alias git_change_remote="git -C ~/my-dotfiles remote set-url origin git@github.com:marc-hg/my-dotfiles.git"
alias git_set_my_dot_files_user="git -C ~/my-dotfiles config --local user.email 'myuser.notexist.wo.wa' && git -C ~/my-dotfiles config --local user.name myuser"
# Sync keys
alias sync-ssh="rsync -a --exclude='.git' --exclude='known_hosts' livb@192.168.0.10:/home/livb/.ssh/ ~/.ssh && git_change_remote && git_set_my_dot_files_user && git -C ~/my-dotfiles pull origin main"
alias sync_ssh="sync-ssh"
# Sync apps
alias sync-apps="rsync -a ~/my-dotfiles/applications/ ~/.local/share/applications/"
alias sync_apps="sync-apps"

# Meta
alias zsh-update="git -C ~/my-dotfiles pull && git -C ~/my-dotfiles submodule foreach --recursive git pull && zsh"
alias zsh_update="zsh-update"
alias zsh-update-force="git restore ~/my-dotfiles && git -C ~/my-dotfiles reset --hard origin/main && git -C ~/my-dotfiles pull && zsh"
alias zsh_update_force="zsh-update-force"
alias zsh_push="cd ~/my-dotfiles && git add . && git commit -m 'changes' && git push origin main && cd -"
alias zsh-push="cd ~/my-dotfiles && git add . && git commit -m 'changes' && git push origin main && cd -"
alias zsh-set-remote="git -C ~/my-dotfiles remote rm origin && git -C ~/my-dotfiles remote add origin git@github:marc-hg/my-dotfiles.git"
alias zsh_set_remote="zsh-set-remote"

# Programs
alias yt="yt-dlp"
alias youtube-dl="yt"
alias yt-audio="yt --extract-audio --audio-format mp3"

# Terminal
alias icat="kitty +kitten icat"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

alias  l='exa -l  --icons'
alias ls='exa -1  --icons'
alias ll='exa -la --icons'
alias ld='exa -lD --icons'

alias in='sudo pacman -S' # install package
alias un='sudo pacman -Rns' # uninstall package
alias up='sudo pacman -Syu' # update system/package/aur
alias pl='pacman -Qs' # list installed package
alias pa='pacman -Ss' # list availabe package
alias pc='sudo pacman -Sc' # remove unused cache
alias po='pacman -Qtdq | sudo pacman -Rns -' # remove unused packages, also try > pacman -Qqd | pacman -Rsu --print -

alias showaliases="echo 'Alias: in -> sudo pacman -S # install package'
echo 'Alias: un -> sudo pacman -Rns # uninstall package'
echo 'Alias: up -> sudo pacman -Syu # update system/package/aur'
echo 'Alias: pl -> pacman -Qs # list installed package'
echo 'Alias: pa -> pacman -Ss # list available package'
echo 'Alias: pc -> sudo pacman -Sc # remove unused cache'
echo 'Alias: po -> pacman -Qtdq | sudo pacman -Rns - # remove unused packages, also try > pacman -Qqd | pacman -Rsu --print -'"

if [[ $TERM == "xterm-kitty" ]]; then
  alias ssh="kitty +kitten ssh"
fi


