#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.fnm:$PATH
# export PATH=$HOME/.z/bin:$PATH
export PATH="$HOME/.local/share/neovim/bin":$PATH
export PATH="/data/data/com.termux/files/home/.local/share/fnm:$PATH"
# . ~/.local/share/z/bin/z.sh
#export PATH="$PATH:./node_modules/.bin"
# 
# 
if  command -v fnm >/dev/null 2>&1; then
    eval "$(fnm env)"
fi
if  command -v zoxide >/dev/null 2>&1; then
    eval "$(zoxide init zsh)"
fi

# eval "`pip completion --zsh`"


